### ISSUE TITLE
cpu only

### ISSUE THREAD

**Issue by kaishijeng** [longcw/yolo2-pytorch#13]
Plan to run this on Raspberry3 board. Does you code run on a CPU only platform?

Thanks,

**Comment by 9thDimension** [comment]
I just ran the demo successfully on a laptop with no nvidia. Comment out lines like https://github.com/longcw/yolo2-pytorch/blob/master/demo.py#L34 and https://github.com/longcw/yolo2-pytorch/blob/master/demo.py#L47 which place tensors onto the GPU memory and you should be OK.

**Comment by kaishijeng** [comment]
Thanks for the info. But the compilation make.sh can't be completed because it needs nvcc to compile roi_pooling. Also utils needs nvcc in order to build. How do you solve this?

**Comment by AsrorWali** [comment]
@kaishijeng Can you tell me how you solved it ?

**Comment by imransalam** [comment]
I have trained a network on GPU but I have to deploy my code on a CPU instance. The test.py script does not seem to work on CPU and gives 'ImportError: No module named _reorg_layer' error on from ._reorg_layer import lib as _lib, ffi as _ffi.
This is probably because make.sh could not be compiled.
Any idea how to achieve this?
@kaishijeng @9thDimension @longcw

**Comment by georgeokelly** [comment]
hi, how do you solve it?

**Comment by qq1243196045** [comment]
I also want use it with pytorch-cpuonly,What should I do?
